version: '3'

services:
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD= postgres123
          - POSTGRES_HOST_AUTH_METHOD=trust
    web:
        build: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
          - .:/app
        links:
          - postgres
        environment:
          - POSTGRES_PORT= 5432
          - POSTGRES_USER= postgres
          - POSTGRES_DATABASE= postgres
          - POSTGRES_HOST= postgres



